name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to main
  workflow_dispatch:  # Allows manual trigger from the Actions tab

permissions:
  contents: write  # Allow pushing to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to generate correct GitInfo

      # Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # Build the site with Hugo
      - name: Build with Hugo
        run: hugo --minify  # Builds the site into the public directory

      # Deploy to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Use the public directory for deployment
          publish_branch: gh-pages  # Deploy to gh-pages branch
