name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main  # Trigger on push to main
  workflow_dispatch:  # Allows manual trigger from the Actions tab

permissions:
  contents: write  # Allow pushing built files to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # Build the site with Hugo, output to the docs folder
      - name: Build with Hugo
        run: hugo --minify -d docs  # Build the site into the docs directory

      # Commit the generated files in the docs directory back to the main branch
      - name: Commit built files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs
          git commit -m "Deploy site to docs from GitHub Actions" || echo "No changes to commit"

      # Push the built files to the main branch
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
